services:
  taylormade:
    build:
      context: .
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_MAP_ID: ${NEXT_PUBLIC_MAP_ID}
    image: ghcr.io/jmedss/taylormade:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
